### ISSUE TITLE
I need Help

### ISSUE THREAD

**Issue by Erquexd** [issam-seghir/discord-clone#7]
CMD
Microsoft Windows [Version 10.0.22631.4317]
(c) Microsoft Corporation. Tüm hakları saklıdır.

D:\Connectify>npm start

> nextjs-discord-clone@0.1.0 start
> next start

  ▲ Next.js 14.2.15
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 325ms
{
  id: 'cm235bw3o0000sf9nm5kq9ckz',
  userId: 'user_2nF4Mv4xBO3Hl6LjhJaQaHqqAAb',
  name: 'Erque',
  email: '****@gmail.com',
  imageUrl: 'https://img.clerk.com/****',
  createdAt: 2024-10-10T10:18:46.213Z,
  updatedAt: 2024-10-10T10:18:46.213Z
}
 ⨯ Error: Cannot find module 'next/dist/compiled/next-server/app-route.runtime.prßod.js'
Require stack:
- D:\Connectify\.next\server\app\api\messages\route.js
- D:\Connectify\node_modules\next\dist\server\require.js
- D:\Connectify\node_modules\next\dist\server\next-server.js
- D:\Connectify\node_modules\next\dist\server\next.js
- D:\Connectify\node_modules\next\dist\server\lib\start-server.js
- D:\Connectify\node_modules\next\dist\cli\next-start.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at D:\Connectify\node_modules\next\dist\server\require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (D:\Connectify\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at 30517 (D:\Connectify\.next\server\app\api\messages\route.js:1:509)
    at t (D:\Connectify\.next\server\webpack-runtime.js:1:128)
    at 73278 (D:\Connectify\.next\server\app\api\messages\route.js:1:2193)
    at t (D:\Connectify\.next\server\webpack-runtime.js:1:128) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Connectify\\.next\\server\\app\\api\\messages\\route.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\require.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\next-server.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\next.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'D:\\Connectify\\node_modules\\next\\dist\\cli\\next-start.js'
  ]
}
 ⨯ Error: Cannot find module 'next/dist/compiled/next-server/app-route.runtime.prßod.js'
Require stack:
- D:\Connectify\.next\server\app\api\messages\route.js
- D:\Connectify\node_modules\next\dist\server\require.js
- D:\Connectify\node_modules\next\dist\server\next-server.js
- D:\Connectify\node_modules\next\dist\server\next.js
- D:\Connectify\node_modules\next\dist\server\lib\start-server.js
- D:\Connectify\node_modules\next\dist\cli\next-start.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at D:\Connectify\node_modules\next\dist\server\require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (D:\Connectify\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at 30517 (D:\Connectify\.next\server\app\api\messages\route.js:1:509)
    at t (D:\Connectify\.next\server\webpack-runtime.js:1:128)
    at 73278 (D:\Connectify\.next\server\app\api\messages\route.js:1:2193)
    at t (D:\Connectify\.next\server\webpack-runtime.js:1:128) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Connectify\\.next\\server\\app\\api\\messages\\route.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\require.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\next-server.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\next.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'D:\\Connectify\\node_modules\\next\\dist\\cli\\next-start.js'
  ]
}
 ⨯ Error: Cannot find module 'next/dist/compiled/next-server/app-route.runtime.prßod.js'
Require stack:
- D:\Connectify\.next\server\app\api\messages\route.js
- D:\Connectify\node_modules\next\dist\server\require.js
- D:\Connectify\node_modules\next\dist\server\next-server.js
- D:\Connectify\node_modules\next\dist\server\next.js
- D:\Connectify\node_modules\next\dist\server\lib\start-server.js
- D:\Connectify\node_modules\next\dist\cli\next-start.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at D:\Connectify\node_modules\next\dist\server\require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (D:\Connectify\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at 30517 (D:\Connectify\.next\server\app\api\messages\route.js:1:509)
    at t (D:\Connectify\.next\server\webpack-runtime.js:1:128)
    at 73278 (D:\Connectify\.next\server\app\api\messages\route.js:1:2193)
    at t (D:\Connectify\.next\server\webpack-runtime.js:1:128) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Connectify\\.next\\server\\app\\api\\messages\\route.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\require.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\next-server.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\next.js',
    'D:\\Connectify\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'D:\\Connectify\\node_modules\\next\\dist\\cli\\next-start.js'
  ]
}
 ⨯ E

**Comment by issam-seghir** [comment]
did you run : `npm install` ?
if so try to delete .next folder or node models and install again :

**Comment by haciosman** [comment]
Hello.
I got everything working without any problems but I'm having problems with the API. I edit the API keys in the env file. But when uploading an image, it gives an error saying invalid api key must start with sk. I check my api keys from the clerk site and they are all correct. How do I solve this problem?

**Comment by issam-seghir** [comment]
> Hello. I got everything working without any problems but I'm having problems with the API. I edit the API keys in the env file. But when uploading an image, it gives an error saying invalid api key must start with sk. I check my api keys from the clerk site and they are all correct. How do I solve this problem?

make sure you follow the doc when config [uploadthing ](https://uploadthing.com)
api start with "sk" is from uploadthing not from clerk
