### ISSUE TITLE
prisma error on start 

### ISSUE THREAD

**Issue by DifficultPhil** [issam-seghir/discord-clone#8]
i install modules, and prisma db push, but i have error:
```
 GET / 500 in 895ms
 GET /favicon.ico 200 in 5ms
   Reload env: .env
 ✓ Compiled in 171ms (2645 modules)
 ⨯ PrismaClientKnownRequestError: 
Invalid `prisma.profile.findUnique()` invocation:


The table `public?pgbouncer=true.Profile` does not exist in the current database.
    at async getCurrentProfile (./src/lib/query.ts:53:21)
    at async SideBar (./src/components/layout/side-bar.tsx:25:21)
digest: "457122122"
 ⨯ PrismaClientKnownRequestError:
Invalid `prisma.profile.findUnique()` invocation:


The table `public?pgbouncer=true.Profile` does not exist in the current database.
    at async initProfile (./src/lib/query.ts:33:21)
    at async Home (page.tsx:19:21)
digest: "2811373818"
 ⨯ PrismaClientKnownRequestError:
Invalid `prisma.profile.findUnique()` invocation:


The table `public?pgbouncer=true.Profile` does not exist in the current database.
    at async getCurrentProfile (./src/lib/query.ts:53:21)
    at async SideBar (./src/components/layout/side-bar.tsx:25:21)
digest: "457122122"
 ⨯ PrismaClientKnownRequestError:
Invalid `prisma.profile.findUnique()` invocation:


The table `public?pgbouncer=true.Profile` does not exist in the current database.
    at async initProfile (./src/lib/query.ts:33:21)
    at async Home (page.tsx:19:21)
digest: "2811373818"
 GET / 500 in 922ms
```

**Comment by issam-seghir** [comment]
Ensure to use the correct Database URL in `.env`  ,
For connection pooling, Prisma requires certain compatibility settings , so consult[ Prisma’s documentation on connection pooling with PgBouncer.](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/pgbouncer)
