### ISSUE TITLE
Prisma error upon starting

### ISSUE THREAD

**Issue by Angus-Developer** [issam-seghir/discord-clone#9]
I get this error upon starting the app and/or when I login

```
○ Compiling / ...
 ✓ Compiled / in 1899ms (2459 modules)
 ○ Compiling /api/socket/io ...
 ✓ Compiled /api/socket/io in 680ms (1614 modules)
 GET /api/socket/io?EIO=4&transport=polling&t=PDM0wgW 200 in 2212ms
 ⨯ PrismaClientKnownRequestError:
Invalid `prisma.profile.findUnique()` invocation:


The table `public.Profile` does not exist in the current database.
    at async getCurrentProfile (./src/lib/query.ts:53:21)
    at async SideBar (./src/components/layout/side-bar.tsx:25:21)
digest: "2335556490"
 ⨯ PrismaClientKnownRequestError:
Invalid `prisma.profile.findUnique()` invocation:


The table `public.Profile` does not exist in the current database.
    at async initProfile (./src/lib/query.ts:33:21)
    at async Home (page.tsx:19:21)
digest: "2414385466"
 GET /?_rsc=z18gi 200 in 2799ms
 ⨯ PrismaClientKnownRequestError:
Invalid `prisma.profile.findUnique()` invocation:


The table `public.Profile` does not exist in the current database.
    at async initProfile (./src/lib/query.ts:33:21)
    at async Home (page.tsx:19:21)
digest: "2414385466"
 ⨯ PrismaClientKnownRequestError:
Invalid `prisma.profile.findUnique()` invocation:


The table `public.Profile` does not exist in the current database.
    at async getCurrentProfile (./src/lib/query.ts:53:21)
    at async SideBar (./src/components/layout/side-bar.tsx:25:21)
digest: "2335556490"
 GET /?_rsc=1n6pm 200 in 504ms
 ✓ Compiled /favicon.ico in 465ms (1643 modules)
 GET /favicon.ico 200 in 573ms
```

**Comment by issam-seghir** [comment]
you need to setup neon db

**Comment by Angus-Developer** [comment]
How do I set it up? I have it connected, but I don't know how to set it up correctly

**Comment by issam-seghir** [comment]
- https://www.prisma.io/docs/orm/overview/databases/neon
- https://neon.tech/docs/guides/prisma
